### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by pando85**
Must angular-animate be included too?

### CODE REVIEW

**Comment by jvandemo** [comment]
@pando85 &mdash; I think the following would be a better choice:

```
"angular": ">=1.2.22 <2"
```

which would mean all 1.x versions larger than `1.2.22` and smaller than `2.x`.

What do you think? Thanks!

**Comment by pando85** [comment]
Yea, that could be better.

**Comment by jvandemo** [comment]
@pando85 &mdash; Ok, great, do you want to update your PR or shall I update it in the next release?

**Comment by pando85** [comment]
@jvandemo as you prefer

**Comment by jvandemo** [comment]
@pando85 &mdash; I have updated the dependency and released as v.2.3.0.

Thank you for helping improve this repository :+1:

**Pull request closed without merging**
