### PR TITLE
Infinite notifications

### PR DESCRIPTION
**Pull request by arekzelechowski**

### CODE REVIEW

**Comment by jvandemo** [comment]
@arekzelechowski &mdash; Thank you for your contribution!

So if I understand correctly, setting `ttl` to a value of `0` will make the notification to be displayed permanently?

Thanks again!

**Comment by arekzelechowski** [comment]
That's right.

Arkadiusz Żelechowski

Dnia 23 lip 2015 o godz. 08:33 Jurgen Van de Moere <notifications@github.com> napisał(a):

**Comment by jvandemo** [comment]
@arekzelechowski &mdash; Ok, sounds good to go.

Can you update the change log in the README.md and add a line for v2.1.3:

- added support for permanent notification using ttl=0

Thanks!

**Comment by arekzelechowski** [comment]
I have updated change log in README.md file.

**Comment by jvandemo** [comment]
@arekzelechowski mdash; Thanks, great work!

Maybe one last thought. A timeout of 0ms is often used in JavaScript to delay a call to the next "tick". What do you think about using -1 (number) or false (boolean) for permanent notifications so it doesn't mentally conflict with existing practices.

Using 0 would break changes for existing users.

So I like your proposal but would prefer to use -1 and false (we can allow both).

What are your thoughts?

**Comment by arekzelechowski** [comment]
You are right, commit is coming in a while with updated code and README.

**Comment by arekzelechowski** [comment]
Did you have a chance to look at the latest changes?

**Comment by jvandemo** [comment]
@arekzelechowski &mdash; I think the condition needs to be rewritten.

In Chrome I get:

```JavaScript
true >= 0
// true
false >= 0
// true
-1 >= 0
// false
```

so I think it should be:

```JavaScript
if(options.ttl === -1 || options.ttl === false){ ... }
```

Since using `-1` is a new feature, the version will also have to be updated to v2.2.0 in bower.json and README.md.

Can you make those last changes? Then everything looks good to go.

Thanks again for all your efforts!

**Comment by jvandemo** [comment]
Closed due to lack of response.

@arekzelechowski &mdash; Feel free to re-open if you still want to work on this. Thanks!

**Comment by jvandemo** [comment]
This has been added in PR #33.

**Comment by arekzelechowski** [comment]
Sorry @jvandemo, didn't have time.

**Comment by jvandemo** [comment]
@arekzelechowski &mdash; No problem, thank you for the update! 👍

**Pull request closed without merging**
